(cl:defpackage simtrack_nodes-srv
  (:use )
  (:export
   "SWITCHCAMERA"
   "<SWITCHCAMERA-REQUEST>"
   "SWITCHCAMERA-REQUEST"
   "<SWITCHCAMERA-RESPONSE>"
   "SWITCHCAMERA-RESPONSE"
   "SWITCHOBJECTS"
   "<SWITCHOBJECTS-REQUEST>"
   "SWITCHOBJECTS-REQUEST"
   "<SWITCHOBJECTS-RESPONSE>"
   "SWITCHOBJECTS-RESPONSE"
  ))

