// Generated by gencpp from file simtrack_nodes/SwitchObjects.msg
// DO NOT EDIT!


#ifndef SIMTRACK_NODES_MESSAGE_SWITCHOBJECTS_H
#define SIMTRACK_NODES_MESSAGE_SWITCHOBJECTS_H

#include <ros/service_traits.h>


#include <simtrack_nodes/SwitchObjectsRequest.h>
#include <simtrack_nodes/SwitchObjectsResponse.h>


namespace simtrack_nodes
{

struct SwitchObjects
{

typedef SwitchObjectsRequest Request;
typedef SwitchObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchObjects
} // namespace simtrack_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simtrack_nodes::SwitchObjects > {
  static const char* value()
  {
    return "4f4cbe3ea9a40859a121fa0687f21d1f";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjects&) { return value(); }
};

template<>
struct DataType< ::simtrack_nodes::SwitchObjects > {
  static const char* value()
  {
    return "simtrack_nodes/SwitchObjects";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjects&) { return value(); }
};


// service_traits::MD5Sum< ::simtrack_nodes::SwitchObjectsRequest> should match 
// service_traits::MD5Sum< ::simtrack_nodes::SwitchObjects > 
template<>
struct MD5Sum< ::simtrack_nodes::SwitchObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simtrack_nodes::SwitchObjects >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtrack_nodes::SwitchObjectsRequest> should match 
// service_traits::DataType< ::simtrack_nodes::SwitchObjects > 
template<>
struct DataType< ::simtrack_nodes::SwitchObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::simtrack_nodes::SwitchObjects >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simtrack_nodes::SwitchObjectsResponse> should match 
// service_traits::MD5Sum< ::simtrack_nodes::SwitchObjects > 
template<>
struct MD5Sum< ::simtrack_nodes::SwitchObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simtrack_nodes::SwitchObjects >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtrack_nodes::SwitchObjectsResponse> should match 
// service_traits::DataType< ::simtrack_nodes::SwitchObjects > 
template<>
struct DataType< ::simtrack_nodes::SwitchObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::simtrack_nodes::SwitchObjects >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMTRACK_NODES_MESSAGE_SWITCHOBJECTS_H
