// Generated by gencpp from file simtrack_nodes/SwitchObjectsResponse.msg
// DO NOT EDIT!


#ifndef SIMTRACK_NODES_MESSAGE_SWITCHOBJECTSRESPONSE_H
#define SIMTRACK_NODES_MESSAGE_SWITCHOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtrack_nodes
{
template <class ContainerAllocator>
struct SwitchObjectsResponse_
{
  typedef SwitchObjectsResponse_<ContainerAllocator> Type;

  SwitchObjectsResponse_()
    : return_code(0)  {
    }
  SwitchObjectsResponse_(const ContainerAllocator& _alloc)
    : return_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _return_code_type;
  _return_code_type return_code;




  typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchObjectsResponse_

typedef ::simtrack_nodes::SwitchObjectsResponse_<std::allocator<void> > SwitchObjectsResponse;

typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsResponse > SwitchObjectsResponsePtr;
typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsResponse const> SwitchObjectsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simtrack_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c285fc637ab43abc6f59f97aab55a3bb";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc285fc637ab43abcULL;
  static const uint64_t static_value2 = 0x6f59f97aab55a3bbULL;
};

template<class ContainerAllocator>
struct DataType< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtrack_nodes/SwitchObjectsResponse";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 return_code\n\
\n\
";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtrack_nodes::SwitchObjectsResponse_<ContainerAllocator>& v)
  {
    s << indent << "return_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.return_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTRACK_NODES_MESSAGE_SWITCHOBJECTSRESPONSE_H
