// Generated by gencpp from file simtrack_nodes/SwitchObjectsRequest.msg
// DO NOT EDIT!


#ifndef SIMTRACK_NODES_MESSAGE_SWITCHOBJECTSREQUEST_H
#define SIMTRACK_NODES_MESSAGE_SWITCHOBJECTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtrack_nodes
{
template <class ContainerAllocator>
struct SwitchObjectsRequest_
{
  typedef SwitchObjectsRequest_<ContainerAllocator> Type;

  SwitchObjectsRequest_()
    : model_names()  {
    }
  SwitchObjectsRequest_(const ContainerAllocator& _alloc)
    : model_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _model_names_type;
  _model_names_type model_names;




  typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchObjectsRequest_

typedef ::simtrack_nodes::SwitchObjectsRequest_<std::allocator<void> > SwitchObjectsRequest;

typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsRequest > SwitchObjectsRequestPtr;
typedef boost::shared_ptr< ::simtrack_nodes::SwitchObjectsRequest const> SwitchObjectsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simtrack_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c8cb040feb9b536dc85426121324844";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c8cb040feb9b536ULL;
  static const uint64_t static_value2 = 0xdc85426121324844ULL;
};

template<class ContainerAllocator>
struct DataType< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtrack_nodes/SwitchObjectsRequest";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] model_names\n\
";
  }

  static const char* value(const ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchObjectsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtrack_nodes::SwitchObjectsRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_names[]" << std::endl;
    for (size_t i = 0; i < v.model_names.size(); ++i)
    {
      s << indent << "  model_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTRACK_NODES_MESSAGE_SWITCHOBJECTSREQUEST_H
