// Generated by gencpp from file simtrack_nodes/SwitchCamera.msg
// DO NOT EDIT!


#ifndef SIMTRACK_NODES_MESSAGE_SWITCHCAMERA_H
#define SIMTRACK_NODES_MESSAGE_SWITCHCAMERA_H

#include <ros/service_traits.h>


#include <simtrack_nodes/SwitchCameraRequest.h>
#include <simtrack_nodes/SwitchCameraResponse.h>


namespace simtrack_nodes
{

struct SwitchCamera
{

typedef SwitchCameraRequest Request;
typedef SwitchCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchCamera
} // namespace simtrack_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simtrack_nodes::SwitchCamera > {
  static const char* value()
  {
    return "c5b9a373078bd18eb6a83f9039d973d8";
  }

  static const char* value(const ::simtrack_nodes::SwitchCamera&) { return value(); }
};

template<>
struct DataType< ::simtrack_nodes::SwitchCamera > {
  static const char* value()
  {
    return "simtrack_nodes/SwitchCamera";
  }

  static const char* value(const ::simtrack_nodes::SwitchCamera&) { return value(); }
};


// service_traits::MD5Sum< ::simtrack_nodes::SwitchCameraRequest> should match 
// service_traits::MD5Sum< ::simtrack_nodes::SwitchCamera > 
template<>
struct MD5Sum< ::simtrack_nodes::SwitchCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simtrack_nodes::SwitchCamera >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtrack_nodes::SwitchCameraRequest> should match 
// service_traits::DataType< ::simtrack_nodes::SwitchCamera > 
template<>
struct DataType< ::simtrack_nodes::SwitchCameraRequest>
{
  static const char* value()
  {
    return DataType< ::simtrack_nodes::SwitchCamera >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simtrack_nodes::SwitchCameraResponse> should match 
// service_traits::MD5Sum< ::simtrack_nodes::SwitchCamera > 
template<>
struct MD5Sum< ::simtrack_nodes::SwitchCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simtrack_nodes::SwitchCamera >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simtrack_nodes::SwitchCameraResponse> should match 
// service_traits::DataType< ::simtrack_nodes::SwitchCamera > 
template<>
struct DataType< ::simtrack_nodes::SwitchCameraResponse>
{
  static const char* value()
  {
    return DataType< ::simtrack_nodes::SwitchCamera >::value();
  }
  static const char* value(const ::simtrack_nodes::SwitchCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMTRACK_NODES_MESSAGE_SWITCHCAMERA_H
