// Generated by gencpp from file simtrack_nodes/SwitchCameraRequest.msg
// DO NOT EDIT!


#ifndef SIMTRACK_NODES_MESSAGE_SWITCHCAMERAREQUEST_H
#define SIMTRACK_NODES_MESSAGE_SWITCHCAMERAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simtrack_nodes
{
template <class ContainerAllocator>
struct SwitchCameraRequest_
{
  typedef SwitchCameraRequest_<ContainerAllocator> Type;

  SwitchCameraRequest_()
    : camera(0)  {
    }
  SwitchCameraRequest_(const ContainerAllocator& _alloc)
    : camera(0)  {
  (void)_alloc;
    }



   typedef uint32_t _camera_type;
  _camera_type camera;




  typedef boost::shared_ptr< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchCameraRequest_

typedef ::simtrack_nodes::SwitchCameraRequest_<std::allocator<void> > SwitchCameraRequest;

typedef boost::shared_ptr< ::simtrack_nodes::SwitchCameraRequest > SwitchCameraRequestPtr;
typedef boost::shared_ptr< ::simtrack_nodes::SwitchCameraRequest const> SwitchCameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simtrack_nodes

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbd8a0bc8265b28f11cccf9a4ebd1448";
  }

  static const char* value(const ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbd8a0bc8265b28fULL;
  static const uint64_t static_value2 = 0x11cccf9a4ebd1448ULL;
};

template<class ContainerAllocator>
struct DataType< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simtrack_nodes/SwitchCameraRequest";
  }

  static const char* value(const ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 camera\n\
";
  }

  static const char* value(const ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchCameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simtrack_nodes::SwitchCameraRequest_<ContainerAllocator>& v)
  {
    s << indent << "camera: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.camera);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMTRACK_NODES_MESSAGE_SWITCHCAMERAREQUEST_H
